version: "3.8"

services:
  mongo1:
    image: mongo:latest
    container_name: mongodb
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27017", "--quiet", "--eval", "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'10.8.1.38:27017',priority:1},{_id:1,host:'10.8.1.37:27017',priority:0.5},{_id:2,host:'10.8.1.39:27017',priority:0.5}]}) }"]
      interval: 5s
      timeout: 30s
      retries: 30
    volumes:
      - "mongodb_data:/data/db"
      - "mongodb_config:/data/configdb"
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge

volumes:
  mongodb_data:
  mongodb_config:
